# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/vivado_ip/eth100_link_tx/eth100_link_tx/eth100_link_tx.cache/wt [current_project]
set_property parent.project_path /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/vivado_ip/eth100_link_tx/eth100_link_tx/eth100_link_tx.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/crc.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/etherlink_pkg.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/dp_dclk_ram_2rdwr.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/dclk_transport.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/bytestream_to_rmii.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/fifo_queue.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/txlink_fsm.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/eth100_link_tx.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/iptop_eth100_link_tx.vhd
}
synth_design -top iptop_eth100_link_tx -part xc7z020clg484-1
write_checkpoint -noxdef iptop_eth100_link_tx.dcp
catch { report_utilization -file iptop_eth100_link_tx_utilization_synth.rpt -pb iptop_eth100_link_tx_utilization_synth.pb }
