# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/vivado_ip/eth100_link_rx/eth100_link_rx.cache/wt [current_project]
set_property parent.project_path /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/vivado_ip/eth100_link_rx/eth100_link_rx.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/ip_export [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/etherlink_pkg.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/fifo_queue.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/rxlink_fsm.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/rxlink_cbuf_ctrl.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/rmii_to_bytestream.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/dp_dclk_ram_wr_rdwr.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/eth100_link_rx.vhd
  /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/src/iptop_eth100_link_rx.vhd
}
synth_design -top iptop_eth100_link_rx -part xc7z020clg484-1
write_checkpoint -noxdef iptop_eth100_link_rx.dcp
catch { report_utilization -file iptop_eth100_link_rx_utilization_synth.rpt -pb iptop_eth100_link_rx_utilization_synth.pb }
