webtalk_init -webtalk_dir /home/jara/ownCloud-pluto/elektronika/zed6_eth100_link/zed6_eth100_link.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 25 23:18:11 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ho5gc7ofcl5kkojlkmvkumqmu5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.3_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1451069470000" -context "sdk\\\\application/1451069470000"
webtalk_add_data -client sdk -key hwid -value "1450975155000" -context "sdk\\\\application/1451069470000"
webtalk_add_data -client sdk -key bspid -value "1450975235000" -context "sdk\\\\application/1451069470000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1451069470000"
webtalk_add_data -client sdk -key os -value "freertos821_xilinx" -context "sdk\\\\application/1451069470000"
webtalk_add_data -client sdk -key apptemplate -value "freertos_hello_world" -context "sdk\\\\application/1451069470000"
webtalk_transmit -clientid 3413171698 -regid "" -xml /home/jara/ownCloud-pluto/elektronika/zed6_eth100_link/zed6_eth100_link.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/jara/ownCloud-pluto/elektronika/zed6_eth100_link/zed6_eth100_link.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/jara/ownCloud-pluto/elektronika/zed6_eth100_link/zed6_eth100_link.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
