# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.cache/wt [current_project]
set_property parent.project_path /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/jara/ownCloud-pluto/elektronika/etherlink-hdl/ip_export [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ZynqDesign.bd
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_processing_system7_0_0/ZynqDesign_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_0/ZynqDesign_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_0/ZynqDesign_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_0/ZynqDesign_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_rst_processing_system7_0_100M_0/ZynqDesign_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_rst_processing_system7_0_100M_0/ZynqDesign_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_rst_processing_system7_0_100M_0/ZynqDesign_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_1/ZynqDesign_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_1/ZynqDesign_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_1/ZynqDesign_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_xbar_0/ZynqDesign_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_2/ZynqDesign_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_2/ZynqDesign_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_gpio_0_2/ZynqDesign_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_ethernetlite_0_0/ZynqDesign_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_ethernetlite_0_0/ZynqDesign_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_ethernetlite_0_0/ZynqDesign_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_axi_ethernetlite_0_0/ZynqDesign_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_mii_to_rmii_0_0/ZynqDesign_mii_to_rmii_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_mii_to_rmii_0_0/ZynqDesign_mii_to_rmii_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_clk_wiz_0_0/ZynqDesign_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_clk_wiz_0_0/ZynqDesign_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_clk_wiz_0_0/ZynqDesign_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ip/ZynqDesign_auto_pc_0/ZynqDesign_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ZynqDesign_ooc.xdc]
set_property is_locked true [get_files /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/ZynqDesign.bd]

read_verilog -library xil_defaultlib /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/sources_1/bd/ZynqDesign/hdl/ZynqDesign_wrapper.v
read_xdc /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/constrs_1/imports/tmp/zedboard_master_XDC_RevD_v1.xdc
set_property used_in_implementation false [get_files /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.srcs/constrs_1/imports/tmp/zedboard_master_XDC_RevD_v1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ZynqDesign_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef ZynqDesign_wrapper.dcp
catch { report_utilization -file ZynqDesign_wrapper_utilization_synth.rpt -pb ZynqDesign_wrapper_utilization_synth.pb }
