webtalk_init -webtalk_dir /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 8 22:34:45 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "v91dffoif5ifnp2urtj92nlssp" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.3_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1452285703000" -context "sdk\\\\hardware/1452285703000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1452285703000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1452285703000"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.3" -context "sdk\\\\hardware/1452285703000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1452285703000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1452285703000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1452285703000"
webtalk_add_data -client sdk -key uid -value "1452285824000" -context "sdk\\\\bsp/1452285824000"
webtalk_add_data -client sdk -key hwid -value "1452285703000" -context "sdk\\\\bsp/1452285824000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1452285824000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1452285824000"
webtalk_add_data -client sdk -key uid -value "1452285825000" -context "sdk\\\\application/1452285825000"
webtalk_add_data -client sdk -key hwid -value "1452285703000" -context "sdk\\\\application/1452285825000"
webtalk_add_data -client sdk -key bspid -value "1452285824000" -context "sdk\\\\application/1452285825000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1452285825000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1452285825000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1452285825000"
webtalk_transmit -clientid 3455528366 -regid "" -xml /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/jara/ownCloud-pluto/elektronika/zed8_eth100_loopback/zed8_eth100_loopback.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
